version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:g
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1999
      - POSTGRES_DB=SkyEng

  pgadminnew:
    image: dpage/pgadmin4:latest
    container_name: pgadminnew
    depends_on:
      - postgres
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: technic47@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1999
    ports:
      - "15050:80"

  service:
    build:
      context: .
    container_name: skyeng
    depends_on:
      - postgres
    restart: always
    ports:
      - "9090:8080"
    environment:
      - DATASOURCE_DRIVER=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/SkyEng
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1999
      - SPRING_JPA_GENERATE-DDL=true